<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.keycloak</groupId>
        <artifactId>keycloak-parent</artifactId>
        <version>26.1.0</version>
    </parent>

    <artifactId>keycloak-2fa-parent</artifactId>
    <name>Keycloak 2fa Parent</name>
    <packaging>pom</packaging>

    <modules>
        <module>phone-provider</module>
        <module>keycloak-email-provider</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <version.keycloak>26.1.0</version.keycloak>
        <commons.validator.version>1.8.0</commons.validator.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-core</artifactId>
                <version>${version.keycloak}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-services</artifactId>
                <version>${version.keycloak}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-server-spi</artifactId>
                <version>${version.keycloak}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-server-spi-private</artifactId>
                <version>${version.keycloak}</version>
                <scope>provided</scope>
            </dependency>

            <!-- phone and sms -->
            <dependency>
                <groupId>com.googlecode.libphonenumber</groupId>
                <artifactId>libphonenumber</artifactId>
                <version>8.13.46</version>
            </dependency>
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>aliyun-java-sdk-core</artifactId>
                <version>4.7.1</version>
            </dependency>
            <dependency>
                <groupId>com.cloopen</groupId>
                <artifactId>java-sms-sdk</artifactId>
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>com.tencentcloudapi</groupId>
                <artifactId>tencentcloud-sdk-java</artifactId>
                <version>3.1.1111</version><!-- 注：这里只是示例版本号，请获取并替换为 最新的版本号 -->
            </dependency>
            <dependency>
                <groupId>com.twilio.sdk</groupId>
                <artifactId>twilio</artifactId>
                <version>10.5.1</version>
            </dependency>
            <dependency>
                <groupId>br.com.totalvoice</groupId>
                <artifactId>totalvoice-java</artifactId>
                <version>1.4.13</version>
            </dependency>
            <dependency>
                <groupId>commons-validator</groupId>
                <artifactId>commons-validator</artifactId>
                <version>${commons.validator.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>