package org.keycloak.federation.rest.provider;

import org.keycloak.federation.rest.model.HashAlgorithm;
import org.keycloak.federation.rest.model.SignAlgorithm;
import org.keycloak.provider.ProviderConfigProperty;
import org.keycloak.provider.ProviderConfigurationBuilder;

import java.util.List;

public class ConfigurationProperties {
    public static final List<ProviderConfigProperty> PROPERTIES = ProviderConfigurationBuilder.create()
            .property().name(RestConstants.SERVER_URL)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Server Url")
            .defaultValue("https://")
            .helpText("Remote repository url")
            .add()

            .property().name(RestConstants.CLIENT_ID)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Client Id")
            .defaultValue("")
            .helpText("Remote repository appId")
            .add()

            .property().name(RestConstants.CLIENT_SECRET)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Client Secret")
            .defaultValue("")
            .helpText("Remote repository appSecret")
            .add()

            .property().name(RestConstants.CLIENT_SIGN_ALGORITHM)
            .type(ProviderConfigProperty.LIST_TYPE)
            .label("Client Sign Algorithm")
            .options(SignAlgorithm.getAllDescriptions())
            .defaultValue(SignAlgorithm.MD5_BASE64.getDesc())
            .helpText("App Sign Algorithm")
            .add()

            .property().name(RestConstants.PARENT_ATTRS)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User List key")
            .defaultValue("users")
            .helpText("User List Key")
            .add()

            .property().name(RestConstants.COUNT_ATTRS)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Total User Count Attribute")
            .defaultValue("count")
            .helpText("Set Total User Count Attribute")
            .add()

            .property().name(RestConstants.USERNAME_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Username Attribute")
            .defaultValue("username")
            .helpText("Set user username attribute")
            .add()

            .property().name(RestConstants.PASSWORD_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Password Attribute")
            .defaultValue("")
            .helpText("Set user password attribute")
            .add()

            .property().name(RestConstants.FIRSTNAME_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Firstname Attribute")
            .defaultValue("")
            .helpText("Set user firstname attribute")
            .add()

            .property().name(RestConstants.LASTNAME_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Lastname Attribute")
            .defaultValue("")
            .helpText("Set user lastname attribute")
            .add()

            .property().name(RestConstants.EMAIL_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User E-mail Attribute")
            .defaultValue("")
            .helpText("Set user e-mail attribute")
            .add()

            .property().name(RestConstants.CREATE_TIME_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Create Time Attribute")
            .defaultValue("")
            .helpText("Set user create time attribute")
            .add()

            .property().name(RestConstants.MODIFY_TIME_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Modify Time Attribute")
            .defaultValue("")
            .helpText("Set user modify time attribute")
            .add()

            .property().name(RestConstants.ENABLED_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Enabled Attribute")
            .defaultValue("")
            .helpText("Set user enabled attribute")
            .add()

            .property().name(RestConstants.EMAIL_VERIFIED_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("User Email Verified Attribute")
            .defaultValue("")
            .helpText("Set user email verified attribute")
            .add()

            .property().name(RestConstants.GROUP_ATTR)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Group Attribute")
            .defaultValue("")
            .helpText("Set user group attribute")
            .add()

            .property().name(RestConstants.PREFIX)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Define prefix for roles and attributes")
            .helpText("size >=2.HTTP Header will gain weight.")
            .add()

            .property().name(RestConstants.UPPERCASE)
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .defaultValue("false")
            .label("Uppercase role/attribute name")
            .helpText("Convert remote roles/attributes to uppercase")
            .add()

            .property().name(RestConstants.ROLE_SYNC)
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .defaultValue("false")
            .label("Enable roles synchronization")
            .helpText("Apply and create remote roles")
            .add()

            //Password synchronization
            .property().name(RestConstants.PASSWORD_SYNC)
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .defaultValue("false")
            .label("Enable password synchronization")
            .helpText("Apply remote password to password")
            .add()

            .property().name(RestConstants.ROLE_CLIENT_SYNC)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Client name to affect roles")
            .helpText("`Empty` to affect roles to realm, `Client name` to affect them to specific client.")
            .add()

            .property().name(RestConstants.ATTR_SYNC)
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .defaultValue("false")
            .label("Enable attributes synchronization")
            .helpText("Apply remote attributes")
            .add()

            .property().name(RestConstants.PASSWORD_HASH_ALGORITHM)
            .type(ProviderConfigProperty.LIST_TYPE)
            .options(HashAlgorithm.getAllDescriptions())
            .defaultValue(HashAlgorithm.SHA256.getDesc())
            .label("Algorithm for hashing password")
            .helpText("Algorithm for hashing password")
            .add()

            .property().name(RestConstants.PASSWORD_HASH_ITERATION)
            .type(ProviderConfigProperty.STRING_TYPE)
            .defaultValue("27500")
            .label("Number of iteration for hashing password")
            .add()
            //
            .property().name(RestConstants.UNCHECK_FEDERATION)
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .defaultValue("false")
            .label("Uncheck federation origin")
            .helpText("Change attributes or roles without controlling federation origin.")
            .add()

            .property().name(RestConstants.NOT_CREATE_USERS)
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .defaultValue("false")
            .label("Not create new users")
            .helpText("Only update existed users")
            .add()

            .property().name(RestConstants.PROXY_ENABLED)
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .label("Use Proxy")
            .helpText("Add Proxy Properties: http(s).proxyHost,http(s).proxyPort")
            .add()

            .property().name(RestConstants.PROXY_HOST)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Set Proxy Host")
            .helpText("Proxy Host")
            .defaultValue("")
            .add()

            .property().name(RestConstants.PROXY_PORT)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Set Proxy Port")
            .helpText("Proxy Port")
            .defaultValue("8080")
            .add()

            .property().name(RestConstants.PAGE_SIZE)
            .type(ProviderConfigProperty.STRING_TYPE)
            .label("Set Request Page Size")
            .helpText("Set Request Page Size of rest api")
            .defaultValue("1000")
            .add()

            .property()
            .name(RestConstants.AUTO_LINKED_IDENTITY_PROVIDER)
            .label("Auto Linked User to Identity Provider")
            .helpText("Auto Linked User to Identity Provider")
            .type(ProviderConfigProperty.BOOLEAN_TYPE)
            .defaultValue("false")
            .add()

            .property()
            .name(RestConstants.IDENTITY_PROVIDER_ALIAS)
            .label("Identity Provider Alias")
            .helpText("If automatic linked of users to identity provider is enabled, fill in the alias of the identity provider here.")
            .type(ProviderConfigProperty.STRING_TYPE)
            .defaultValue("")
            .add()

            .build();
}
